# Generated by Django 4.2.1 on 2023-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='usernmae')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('start_period', models.DateField(max_length=64, verbose_name='start period')),
                ('end_period', models.DateField(max_length=64, verbose_name='end period')),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'user',
            },
        ),
    ]
