# Generated by Django 4.2.1 on 2023-06-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('weather', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
