# Generated by Django 4.2.1 on 2023-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='weather',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
