# Generated by Django 4.2.1 on 2023-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0002_alter_diary_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='drawing',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='drawing/'),
        ),
    ]
