# Generated by Django 4.2.1 on 2023-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0003_diary_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
