# Generated by Django 4.2.1 on 2023-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0004_alter_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
