# Generated by Django 4.2.1 on 2023-06-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0006_alter_diary_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='drawing/'),
        ),
    ]
