# Generated by Django 4.2.1 on 2023-06-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('Detail', '0009_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
